Allow Redirect component to accept Route object as `to`
atlassian-labs/react-resource-router pull request #108
Opened 2021-12-21 02:54 UTC by jpqne

2022-01-09 23:51 UTC, JakeLane requested changes

2022-01-09 23:51 UTC, JakeLane commented on src/controllers/redirect/index.tsx
> +      basePath: actions.getBasePath() as any,
Is there a reason the type is casted to any here?

2022-01-09 23:51 UTC, JakeLane commented on src/controllers/redirect/types.ts
> +  to: Location | Route | string;
I think the flow type should be updated too

2022-02-12 07:39 UTC, albertogasparin submitted a review, later dismissed

2022-02-13 23:32 UTC, JakeLane submitted a review, later dismissed

2022-02-13 23:40 UTC, liamqma approved these changes

2022-02-13 23:47 UTC, liamqma approved these changes

2022-02-13 23:53 UTC, JakeLane approved these changes

2022-02-13 23:54 UTC, merged